### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tftangming** [tatsy/L0Denoising#1]
What version of your openMesh? I met some problem which seems to be related with the installed openMesh.

**Comment by tatsy** [comment]
I'm not really sure about the version because this program is rather old. I remember that it is lower than v6. So, it is possible that this program will not be built with the latest one.

**Comment by tftangming** [comment]
@tatsy Thanks for your suggest, I can success to build the resource using openMesh5.0. But I find your code for constructing the matrix R and D seems to be opposite, which is confusing me. Can you give me some advice? Thanks very much!

**Comment by tatsy** [comment]
Hi @tftangming,

So, you mean my program is now working with v5.0? Or, just you suggest the matrix naming for R and D are confusing?

**Comment by tatsy** [comment]
Because this repo is rather outdated, I re-implemented L0 mesh smoothing in my another project:
https://github.com/tatsy/tinymesh

See the source code for your reference.
https://github.com/tatsy/tinymesh/blob/d7b0908ef0cbb91303c8e76e17eee977b6f4450c/src/tinymesh/filters/denoise.cpp#L181
