### ISSUE TITLE
About denoise

### ISSUE THREAD

**Issue by bytemanxie** [tatsy/L0Denoising#3]
Can you explain what this step is doing
![1702431763050](https://github.com/tatsy/L0Denoising/assets/140388812/77d02359-f275-478b-876c-c415d9d86e52)

**Comment by tatsy** [comment]
Can you read the original article, please? Here is not the QA forum.
https://people.engr.tamu.edu/schaefer/research/L0Smoothing.pdf

**Comment by bytemanxie** [comment]
sorry, I am a beginner .I have read this paper.I don't know how the optimization problem in the paper is transformed into solving a system of linear equations.
